//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paynova.Api.Client.UnitTests.HttpRequestFactories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paynova.Api.Client.UnitTests.HttpRequestFactories.ExpectedJson", typeof(ExpectedJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:12.75,&quot;lineItems&quot;:[{&quot;id&quot;:&quot;id:1&quot;,&quot;articleNumber&quot;:&quot;num:1&quot;,&quot;name&quot;:&quot;Some article1&quot;,&quot;description&quot;:&quot;A nice little Some article 1&quot;,&quot;productUrl&quot;:&quot;http://foo.com/articles/1&quot;,&quot;quantity&quot;:1,&quot;unitMeasure&quot;:&quot;st&quot;,&quot;unitAmountExcludingTax&quot;:2.25,&quot;taxPercent&quot;:25.00,&quot;totalLineTaxAmount&quot;:0.5625,&quot;totalLineAmount&quot;:2.8125,&quot;lineItemGroupKey&quot;:&quot;ODD&quot;},{&quot;id&quot;:&quot;id:2&quot;,&quot;articleNumber&quot;:&quot;num:2&quot;,&quot;name&quot;:&quot;Some article2&quot;,&quot;description&quot;:&quot;A nice little Som [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnnulAuth_With_LineItems {
            get {
                return ResourceManager.GetString("AnnulAuth_With_LineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:12.75,&quot;lineItems&quot;:[{&quot;id&quot;:&quot;id:1&quot;,&quot;articleNumber&quot;:&quot;num:1&quot;,&quot;name&quot;:&quot;Flight - A to B1&quot;,&quot;description&quot;:&quot;A nice little Flight - A to B 1&quot;,&quot;productUrl&quot;:&quot;http://foo.com/articles/1&quot;,&quot;quantity&quot;:1,&quot;unitMeasure&quot;:&quot;st&quot;,&quot;unitAmountExcludingTax&quot;:2.25,&quot;taxPercent&quot;:25.00,&quot;totalLineTaxAmount&quot;:0.5625,&quot;totalLineAmount&quot;:2.8125,&quot;lineItemGroupKey&quot;:&quot;Air&quot;,&quot;travelData&quot;:{&quot;bookingReference&quot;:&quot;Booking ref 1&quot;,&quot;travelSegments&quot;:[{&quot;segmentType&quot;:&quot;Air&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnnulAuth_With_TravelLineItems {
            get {
                return ResourceManager.GetString("AnnulAuth_With_TravelLineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderId&quot;:&quot;499de2b4-e55e-433b-bf33-fa39efc0ce68&quot;,&quot;authorizationType&quot;:&quot;InvoicePayment&quot;,&quot;totalAmount&quot;:125.50,&quot;paymentMethodId&quot;:311,&quot;paymentMethodProductId&quot;:&quot;DirectInvoice&quot;,&quot;paymentChannelId&quot;:1}.
        /// </summary>
        internal static string AuthorizeInvoice {
            get {
                return ResourceManager.GetString("AuthorizeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderNumber&quot;:&quot;order_123&quot;,&quot;orderDescription&quot;:&quot;My order description&quot;,&quot;currencyCode&quot;:&quot;SEK&quot;,&quot;totalAmount&quot;:8.4375,&quot;salesChannel&quot;:&quot;My sales channel&quot;,&quot;salesLocationId&quot;:&quot;My sales location id&quot;,&quot;customer&quot;:{&quot;customerId&quot;:&quot;My customer id&quot;,&quot;emailAddress&quot;:&quot;sample@mycustomer.com&quot;,&quot;name&quot;:{&quot;title&quot;:&quot;Mr.&quot;,&quot;firstName&quot;:&quot;John&quot;,&quot;middleNames&quot;:&quot;Doe&quot;,&quot;lastName&quot;:&quot;Testsson&quot;,&quot;suffix&quot;:&quot;Sr.&quot;},&quot;homeTelephone&quot;:&quot;+4681234567&quot;,&quot;workTelephone&quot;:&quot;+4682345678&quot;,&quot;mobileTelephone&quot;:&quot;+467099999999&quot;},&quot;billTo&quot;:{&quot;name&quot;:{&quot;companyName&quot;:&quot;Test company&quot;},&quot;ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailedCreateOrder_With_LineItems {
            get {
                return ResourceManager.GetString("DetailedCreateOrder_With_LineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderNumber&quot;:&quot;order_123&quot;,&quot;orderDescription&quot;:&quot;My order description&quot;,&quot;currencyCode&quot;:&quot;SEK&quot;,&quot;totalAmount&quot;:8.4375,&quot;salesChannel&quot;:&quot;My sales channel&quot;,&quot;salesLocationId&quot;:&quot;My sales location id&quot;,&quot;customer&quot;:{&quot;customerId&quot;:&quot;My customer id&quot;,&quot;emailAddress&quot;:&quot;sample@mycustomer.com&quot;,&quot;name&quot;:{&quot;title&quot;:&quot;Mr.&quot;,&quot;firstName&quot;:&quot;John&quot;,&quot;middleNames&quot;:&quot;Doe&quot;,&quot;lastName&quot;:&quot;Testsson&quot;,&quot;suffix&quot;:&quot;Sr.&quot;},&quot;homeTelephone&quot;:&quot;+4681234567&quot;,&quot;workTelephone&quot;:&quot;+4682345678&quot;,&quot;mobileTelephone&quot;:&quot;+467099999999&quot;},&quot;billTo&quot;:{&quot;name&quot;:{&quot;companyName&quot;:&quot;Test company&quot;},&quot;ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailedCreateOrder_With_TravelLineItems {
            get {
                return ResourceManager.GetString("DetailedCreateOrder_With_TravelLineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderId&quot;:&quot;a83aec2a-f9fd-4193-978a-83b3e474769d&quot;,&quot;totalAmount&quot;:8.4375,&quot;paymentChannelId&quot;:1,&quot;paymentMethods&quot;:[{&quot;id&quot;:1},{&quot;id&quot;:2}],&quot;customData&quot;:[{&quot;key&quot;:&quot;key1&quot;,&quot;value&quot;:&quot;value1&quot;},{&quot;key&quot;:&quot;key2&quot;,&quot;value&quot;:&quot;value2&quot;}],&quot;sessionTimeout&quot;:180,&quot;routingIndicator&quot;:&quot;some indicator&quot;,&quot;fraudScreeningProfile&quot;:&quot;some fraud profile&quot;,&quot;interfaceOptions&quot;:{&quot;interfaceId&quot;:5,&quot;customerLanguageCode&quot;:&quot;SWE&quot;,&quot;urlRedirectSuccess&quot;:&quot;https://foo.com/payments/success&quot;,&quot;urlRedirectCancel&quot;:&quot;https://foo.com/payments/cancel&quot;,&quot;urlRedirectPending&quot;:&quot;https [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailedInitPaymentRequest_With_LineItems {
            get {
                return ResourceManager.GetString("DetailedInitPaymentRequest_With_LineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderId&quot;:&quot;a83aec2a-f9fd-4193-978a-83b3e474769d&quot;,&quot;totalAmount&quot;:8.4375,&quot;paymentChannelId&quot;:1,&quot;paymentMethods&quot;:[{&quot;id&quot;:1},{&quot;id&quot;:2}],&quot;customData&quot;:[{&quot;key&quot;:&quot;key1&quot;,&quot;value&quot;:&quot;value1&quot;},{&quot;key&quot;:&quot;key2&quot;,&quot;value&quot;:&quot;value2&quot;}],&quot;sessionTimeout&quot;:180,&quot;routingIndicator&quot;:&quot;some indicator&quot;,&quot;fraudScreeningProfile&quot;:&quot;some fraud profile&quot;,&quot;interfaceOptions&quot;:{&quot;interfaceId&quot;:5,&quot;customerLanguageCode&quot;:&quot;SWE&quot;,&quot;urlRedirectSuccess&quot;:&quot;https://foo.com/payments/success&quot;,&quot;urlRedirectCancel&quot;:&quot;https://foo.com/payments/cancel&quot;,&quot;urlRedirectPending&quot;:&quot;https [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetailedInitPaymentRequest_With_TravelLineItems {
            get {
                return ResourceManager.GetString("DetailedInitPaymentRequest_With_TravelLineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:112.75,&quot;invoiceId&quot;:&quot;invoice1&quot;,&quot;lineItems&quot;:[{&quot;id&quot;:&quot;id:1&quot;,&quot;articleNumber&quot;:&quot;num:1&quot;,&quot;name&quot;:&quot;Some article1&quot;,&quot;description&quot;:&quot;A nice little Some article 1&quot;,&quot;productUrl&quot;:&quot;http://foo.com/articles/1&quot;,&quot;quantity&quot;:1,&quot;unitMeasure&quot;:&quot;st&quot;,&quot;unitAmountExcludingTax&quot;:2.25,&quot;taxPercent&quot;:25.00,&quot;totalLineTaxAmount&quot;:0.5625,&quot;totalLineAmount&quot;:2.8125,&quot;lineItemGroupKey&quot;:&quot;ODD&quot;},{&quot;id&quot;:&quot;id:2&quot;,&quot;articleNumber&quot;:&quot;num:2&quot;,&quot;name&quot;:&quot;Some article2&quot;,&quot;descrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinalizeAuth_With_LineItems {
            get {
                return ResourceManager.GetString("FinalizeAuth_With_LineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:112.75,&quot;invoiceId&quot;:&quot;invoice1&quot;,&quot;lineItems&quot;:[{&quot;id&quot;:&quot;id:1&quot;,&quot;articleNumber&quot;:&quot;num:1&quot;,&quot;name&quot;:&quot;Flight - A to B1&quot;,&quot;description&quot;:&quot;A nice little Flight - A to B 1&quot;,&quot;productUrl&quot;:&quot;http://foo.com/articles/1&quot;,&quot;quantity&quot;:1,&quot;unitMeasure&quot;:&quot;st&quot;,&quot;unitAmountExcludingTax&quot;:2.25,&quot;taxPercent&quot;:25.00,&quot;totalLineTaxAmount&quot;:0.5625,&quot;totalLineAmount&quot;:2.8125,&quot;lineItemGroupKey&quot;:&quot;Air&quot;,&quot;travelData&quot;:{&quot;bookingReference&quot;:&quot;Booking ref 1&quot;,&quot;travelSegment [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinalizeAuth_With_TravelLineItems {
            get {
                return ResourceManager.GetString("FinalizeAuth_With_TravelLineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;totalAmount&quot;:112.75,&quot;paymentChannelId&quot;:1,&quot;currencyCode&quot;:&quot;SEK&quot;,&quot;countryCode&quot;:&quot;SE&quot;,&quot;languageCode&quot;:&quot;SWE&quot;}.
        /// </summary>
        internal static string GetPaymentOptions {
            get {
                return ResourceManager.GetString("GetPaymentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:12.75,&quot;invoiceId&quot;:&quot;invoice1&quot;,&quot;lineItems&quot;:[{&quot;id&quot;:&quot;id:1&quot;,&quot;articleNumber&quot;:&quot;num:1&quot;,&quot;name&quot;:&quot;Some article1&quot;,&quot;description&quot;:&quot;A nice little Some article 1&quot;,&quot;productUrl&quot;:&quot;http://foo.com/articles/1&quot;,&quot;quantity&quot;:1,&quot;unitMeasure&quot;:&quot;st&quot;,&quot;unitAmountExcludingTax&quot;:2.25,&quot;taxPercent&quot;:25.00,&quot;totalLineTaxAmount&quot;:0.5625,&quot;totalLineAmount&quot;:2.8125,&quot;lineItemGroupKey&quot;:&quot;ODD&quot;},{&quot;id&quot;:&quot;id:2&quot;,&quot;articleNumber&quot;:&quot;num:2&quot;,&quot;name&quot;:&quot;Some article2&quot;,&quot;descript [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefundPayment_With_LineItems {
            get {
                return ResourceManager.GetString("RefundPayment_With_LineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:12.75,&quot;invoiceId&quot;:&quot;invoice1&quot;,&quot;lineItems&quot;:[{&quot;id&quot;:&quot;id:1&quot;,&quot;articleNumber&quot;:&quot;num:1&quot;,&quot;name&quot;:&quot;Flight - A to B1&quot;,&quot;description&quot;:&quot;A nice little Flight - A to B 1&quot;,&quot;productUrl&quot;:&quot;http://foo.com/articles/1&quot;,&quot;quantity&quot;:1,&quot;unitMeasure&quot;:&quot;st&quot;,&quot;unitAmountExcludingTax&quot;:2.25,&quot;taxPercent&quot;:25.00,&quot;totalLineTaxAmount&quot;:0.5625,&quot;totalLineAmount&quot;:2.8125,&quot;lineItemGroupKey&quot;:&quot;Air&quot;,&quot;travelData&quot;:{&quot;bookingReference&quot;:&quot;Booking ref 1&quot;,&quot;travelSegments [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefundPayment_With_TravelLineItems {
            get {
                return ResourceManager.GetString("RefundPayment_With_TravelLineItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:12.75}.
        /// </summary>
        internal static string SimpleAnnulAuth {
            get {
                return ResourceManager.GetString("SimpleAnnulAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderNumber&quot;:&quot;order_123&quot;,&quot;currencyCode&quot;:&quot;SEK&quot;,&quot;totalAmount&quot;:112.53}.
        /// </summary>
        internal static string SimpleCreateOrder {
            get {
                return ResourceManager.GetString("SimpleCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:112.75,&quot;invoiceId&quot;:&quot;invoice1&quot;}.
        /// </summary>
        internal static string SimpleFinalizeAuth {
            get {
                return ResourceManager.GetString("SimpleFinalizeAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;orderId&quot;:&quot;a83aec2a-f9fd-4193-978a-83b3e474769d&quot;,&quot;totalAmount&quot;:112.53,&quot;paymentChannelId&quot;:1,&quot;interfaceOptions&quot;:{&quot;interfaceId&quot;:5,&quot;customerLanguageCode&quot;:&quot;SWE&quot;,&quot;urlRedirectSuccess&quot;:&quot;https://foo.com/payments/success&quot;,&quot;urlRedirectCancel&quot;:&quot;https://foo.com/payments/cancel&quot;,&quot;urlRedirectPending&quot;:&quot;https://foo.com/payments/pending&quot;}}.
        /// </summary>
        internal static string SimpleInitPayment {
            get {
                return ResourceManager.GetString("SimpleInitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;transactionId&quot;:&quot;transaction1&quot;,&quot;orderId&quot;:&quot;7a246c7b-d97f-461d-9da8-e6f710f319a1&quot;,&quot;totalAmount&quot;:12.75,&quot;invoiceId&quot;:&quot;invoice1&quot;}.
        /// </summary>
        internal static string SimpleRefundPayment {
            get {
                return ResourceManager.GetString("SimpleRefundPayment", resourceCulture);
            }
        }
    }
}
